### ISSUE TITLE
数据来源？

### ISSUE THREAD

**Issue by jimmy-walker** [antct/city-vein#2]
非常棒的项目，请问数据是从哪里得到的呢？

**Comment by secsilm** [comment]
粗略看了一下代码，线路数据应该来自 8684，再利用百度地图 API 获得经纬度

**Comment by antct** [comment]
> 非常棒的项目，请问数据是从哪里得到的呢？

是的，公交数据来源于8684，先获取所有线路，再依次获取所有站点。
