### ISSUE TITLE
程序执行

### ISSUE THREAD

**Issue by faithxie** [antct/city-vein#3]
运行main.py 当程序执行到 `_get_line_info`：

 ```
try:
            logger.info("try")
            response = requests.get(targetUrl, headers=self.headers)
            content = response.content
            content = dict(eval(content))
       
            logger.info("polyline info: %s" % content)(不输出)
            
```

就不执行的了，也不报异常，  咋回事？ 求指导

**Comment by faithxie** [comment]
重复执行多次，卡在不同路线上。看似是网络请求不到就会一直等待？换了网络也是 ，执行不完，总是卡在某个线路上

**Comment by antct** [comment]
emm，请问81行和158行输入正确的key了吗，这个key是可以在高德地图api获取~

**Comment by faithxie** [comment]
输入了 数据也能获取  但是程序执行 try    只执行几次，到某个线路就不执行了，尝试多次，每次卡在不同的线路上，排除是线路的问题。try 也不报异常   困惑~

**Comment by antct** [comment]
emmm，我看了一下我的key配置，一个key是web服务，一个key是web端的。
请问这一部分self._get_all_lines()是能完全执行的吗？
_get_line_info是执行了若干之后出错吗，卡住的时候能具体描述一下吗？

**Comment by faithxie** [comment]
**### 第一次运行**：
日志显示在try 不再执行


![image](https://user-images.githubusercontent.com/19542104/58698156-6060c600-83cd-11e9-928b-b904488d7765.png)
**### 再次运行**：
停止后再次运行

![image](https://user-images.githubusercontent.com/19542104/58698373-b9c8f500-83cd-11e9-88ca-7f327865af05.png)


感谢~

**Comment by antct** [comment]
您好 我重新看了一下代码和提供的运行截图 确实很诡异
请问能提供一下爬取的是哪个城市吗

**Comment by faithxie** [comment]
试了多个城市 都是这样  例如 亳州 bozhou  ,是不是两个key的问题，会有请求限制？请问 哪个用web服务的key，我使用web服务的key之后 提示USERKEY_PLAT_NOMATCH,所以只使用的web端的key 。再：window环境运行的还是Linux？是不是文件读写问题。

**Comment by antct** [comment]
_get_line_info中对应的key是Web端key，_get_city_info中对应的key是Web服务key。
亳州在我这里运行正常，已经添加了这个数据。可以在对应的GitHub Page里查看，最后一个城市。
运行的环境是Linux，应该和环境关系不大。

**Comment by faithxie** [comment]
谢谢，辛苦了
