### ISSUE TITLE
刚搞完深圳的效果，基于高德地图，发现你这有这个，真是醉……

### ISSUE THREAD

**Issue by buzhangsan** [antct/city-vein#4]
你这data的数据的坐标是高德的还是百度到？

**Comment by antct** [comment]
数据是高德的

**Comment by buzhangsan** [comment]
数据源是高德的吧，然后shenzhen.data里面的是百度到吧？
昨晚又看了下你的代码，我的思路和你的差不多，公交网站上获取线路列表，然后通过高德请求列表中的线路获取path的经纬度，不过我用的amp_eachrt.js把高德结合echart展示出来省略了经纬度转化这一步

**Comment by antct** [comment]
emm，我这里应该所有的数据都是高德的，最后是用echarts~
